# Generated by Django 4.1.4 on 2023-01-06 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ads_options_alter_categories_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ads.categories'),
        ),
        migrations.AddField(
            model_name='ads',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='images/'),
        ),
    ]
