# Generated by Django 4.1.4 on 2023-01-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_ads_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
